### ISSUE TITLE
[Jose Luis Reguera](w4-project_ETL)

### ISSUE THREAD

**Issue by jose-luis666** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#10]
https://github.com/jose-luis666/proyecto_etl.git

**Comment by OrianAmpuero** [comment]
Muy bien Selu! Haz aplicado cada uno de los consejos dados las semanas anteriores, se nota el curro en cuanto a repo y código. El readme bien explicado y las carpetas correctas con sus archivos; la ETL está bien desarrollada, comentada para un futuro poder apoyarte y el final en SQL muy bien. De verdad que me dejas corta para decirte algo de mejora, solo animarte a seguir así!!
