### ISSUE TITLE
[Nerea Riveiro](w4-project_ETL)

### ISSUE THREAD

**Issue by NereaRiveiro** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#16]
https://github.com/NereaRiveiro/Galician_who.git

**Comment by NereaRiveiro** [comment]
https://github.com/NereaRiveiro/MetaArtists.git nuevo enlace

**Comment by OrianAmpuero** [comment]
Bien Nerea! En cuanto al desarrollo del readme esta correcto y el repo muy bien organizado en sus carpetas, aunque tienes un archivo que da error 'intromongos.ipynb' y por otro lado, los archivos de la carpeta data tiene como todo ahí junto que yo prefiero separar los notebooks trabajados a los csv limpios. La ETL está básica pero entiendo el deadline que tienen de solo 3 días, espero que puedas seguir mejorándolo y enriqueciéndolo como dices en el readme. 
Animo que vas bien!!
