### ISSUE TITLE
[Ignacio Romero][w4-project_ETL]

### ISSUE THREAD

**Issue by Linxx333** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#17]
https://github.com/Linxx333/MrLinx-Data-ETL

**Comment by OrianAmpuero** [comment]
Excelente trabajo Nacho! En cuanto a la extracción has usado lo varios métodos y las 3 fuentes que pedíamos, donde lograste enriquecer tus datos y unificarlos para cargarlo en SQL. La limpieza con sus funciones bien aplicadas y como buena practica importadas desde tu archivo .py.
Mejoraste el readme y se nota, siempre hay mejoras como detalles ortográficos que entiendo por el apuro se pasan por alto, además de que trates de usar en .gitignore para esos archivos que no se ven bien en tu proyecto como un archivo 'prueba' que tienes por ahí pero confío que saldrás de aquí con eso bien interiorizado ya que por lo demás todo esta muy bien hecho.
Sigue así!!
