### ISSUE TITLE
[Luis Galdeano](w4-project_ETL)

### ISSUE THREAD

**Issue by LuisGaldeano** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#18]
https://github.com/LuisGaldeano/Foodify_ETL

**Comment by OrianAmpuero** [comment]
Excelente Luis! Ya te lo he dicho en persona pero te repito que me parece genial cada paso que has hecho para la creación y desarrollo del proyecto, el readme y el repo muy bien. Solo me dejaste un punto y es algunos archivos por fuera de carpetas, pero sin más. 
Espero con ansias tu proyecto final y ánimo!!
