### ISSUE TITLE
[Javier R.](w4-project_ETL)

### ISSUE THREAD

**Issue by jrodrisanz** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#19]
https://github.com/jrodrisanz/ProyectoETL

**Comment by OrianAmpuero** [comment]
Buen proyecto Javier! En cuanto al repo esta organizado y el readme desarrollado correctamente. El proceso de ETL bien, el código comentado como debe de ser para que en un futuro te ayudes pero ten cuidado con los errores que se printean y no los corriges porque queda mal el output así; de resto vas bien, se que te ha costado parte del escrapeo pero al final salió y te animo a seguir a tope.
