### ISSUE TITLE
[Guillermo Lozano Juanco](Proyecto_ETL)

### ISSUE THREAD

**Issue by GuilleJuanco** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#2]
https://github.com/GuilleJuanco/Proyecto_ETL

**Comment by CharlyKill7** [comment]
Buen proyecto, Guille. Algunos comentarios:

- En cuanto al repo, bien la estructura en carpetas. El readme me gusta. En una época donde todos ponen fotos y virguerías, tú tienes lo esencial: de qué va el proyecto, cuales son los pasos y dónde puedo encontrarlos. 
- Y lo mismo puedo decir de tus notebooks: vas a lo esencial. Uno para todo tu proceso de extracción y transformación, más el archivo de carga. 
- Bien la carpeta de imágenes, muestras las tablas ya en SQL y eso está bien, aunque me hubiera gustado que hicieras algun join para ver la tabla total enriquecida.

En cuanto a la exposición:

-	Mal exponer sentado, aunque sea más cómodo por el ordenador.
-	Un lenguaje quizá demasiado informal, que ahora en clase puede valer, pero intenta practicar para exposiciones más serias como el proyecto final o futuras presentaciones en el trabajo. 
-	Intenta enseñar menos código y contar más la historia, centrándote en lo que buscabas y lo que obtuviste, más que en el proceso técnico.

En general, buen proyecto Guille. Sin flotrituras, vas al grano y eso está bien. Te animo no obstante a salirte de tu zona de confort e intentar probar cosas, tanto de fondo como de forma, que te lleven al siguiente nivel. 

¡Ánimo y sigue así!
