### ISSUE TITLE
[LORENZO IMIZCOZ](w4-project_ETL)

### ISSUE THREAD

**Issue by Lorensou** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#21]
https://github.com/Lorensou/-w4-project_ETL

**Comment by OrianAmpuero** [comment]
Buen trabajo Lorenzo! El repo en general bien y el readme corto pero justo para explicar lo que hiciste, quizás explicar un poco más con imágenes por ejemplo el ERD de SQL; lo que sí es que falta una carpeta, por ejemplo 'SRC' para guardar los notebooks de trabajo donde está la ETL. La carpeta de SQL donde hay 3 archivos, pendiente porque uno de ellos no abre y entiendo que es muy pesado y los otros dos como consejo no los tendría ya que son dos queries sin más que no explican mucho y son una línea cada uno. En cuanto al escrapeo y limpieza bien, quizás algo reducido de trabajo pero se ha logrado el objetivo y creo que puedes seguir trabajando en ello.
Te animo a seguir a tope y ánimo en estas semanas que quedan!

**Comment by OrianAmpuero** [comment]
En cuanto a la presentación:
- Muy bien exponer de pie.
- Intenta no dar la espalda a parte de la audiencia. Ciertos ratos, al mirar solo una pantalla, los del otro lado sólo te ven la espalda.
- Un poco corto, intenta contarlo como una pequeña historia para interesar al público, si es posible, y así lo alargas un poco.
