### ISSUE TITLE
[joe sebastian]( w4-project_ETL)

### ISSUE THREAD

**Issue by joeSL-ms** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#22]
https://github.com/joeSL-ms/ProyectoNas

**Comment by OrianAmpuero** [comment]
Bien Joe! En cuanto al repo no hay mucho que organizar porque no tienes varios archivos, haría falta quizás el ERD de SQL, te aconsejo que las funciones también las tengas en otro archivo y el readme más desarrollado ya que es la portada de tu trabajo y lo primero que ven los recruiters.
La ETL en general bien, ya que se ve el curro en las funciones creadas, intenta que no se queden los errores en el output y el rellenar los datos solo con un 'desconocido' no es enriquecer, hay que mostrar un poco más de criterio al rellenar pero vas muy bien así que ánimo.
