### ISSUE TITLE
[Juan Gouveia](w4-project_ETL)

### ISSUE THREAD

**Issue by JuanGouveia** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#24]
https://github.com/JuanGouveia/ETL-Project

**Comment by OrianAmpuero** [comment]
Muy bien Juan!! En cuanto a la extracción de datos se ve todo el curro con los métodos y fuentes que pedimos; la limpieza igual, está bien pero me falta ver comentarios en cada paso que en un futuro te ayudará y a quien vea tu proyecto, recuerda acortar el output y al final de todo, las tablas tienen nulos así que recuerda que hay que rellenar antes de guardar y cargar. 
Y el repo muy bien organizado con sus carpetas y has usado el .gitignore, además el readme está bien descrito y desarrollado.
Vas bien, así que animoo!!
