### ISSUE TITLE
[Carolina Rivera](w4-project_ETL)

### ISSUE THREAD

**Issue by carolinariveraa** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#3]
https://github.com/carolinariveraa/ETL

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Carolina. Permíteme algunos comentarios:

- El repo es muy correcto, con la distribución en carpetas, etc. El readme, aunque está muy bien, tal vez queda un poco largo, por lo que te recomiendo explayarte algo menos en las conclusiones. Una buena forma de reducir el tamaño pero mantener toda la info es usar los desplegables que tienes para las querys de SQL. Así el primer vistazo no agobia por longitud, pero el que está leyéndolo con interés puede optar por ampliar la información facilmente. 
- Respecto al primer notebook, el de tu.csv principal, me he fijado en que la mayoría de registros que tienes corresponden a 2023, pero sólo a los meses de enero, febrero y marzo. Es por eso que en tu query de crímenes agrupados por mes hay tantas diferencias. Te recomendaría 2022 por estar completo, pero si te fijas tiene muchos más datos en diciembre que en el resto del año. Es posible que la recolección más exhaustiva de los datos se venga haciendo sólo desde entonces, por lo que quizá es pronto para sacar conclusiones por meses con ese dataset. Recuerda también, respecto a este primer notebook, evitar hacer importaciones que no usas, como todas las de Selenium. 
- La extracción y transformación en los otros dos notebooks está bien ejecutada, sin complicarte en exceso y, precisamente por eso, se nota que sabes qué buscas cuando extraes y esa es una gran habilidad en data. Y, por supuesto, gran visualización para un proyecto que no la requería. Te felicito por investigar y utilizar folium como lo has hecho. Esa actitud de visualizar que traes desde el primer proyecto denota una perspectiva amplia: no te limitas a hacer lo que toca con los datos; también estás pensando en qué significan ya desde la limpieza.
- En cuanto a la exportación a SQL, queda claro por la explicación del notebook que lo entiendes bien, pero ya que estás, un .png del diagrama en la carpeta de pics no hubiera estado de más.

En general, muy buen trabajo. La conclusión de no poder sacar conclusiones estrictas también me parece adecuada. Intenta mejorar esos pequeños detalles que te cuento, que vas como un cohete 🚀🚀 

¡Sigue así!
