### ISSUE TITLE
[Anton Utray]( w4-project_ETL)

### ISSUE THREAD

**Issue by Anton-Utray** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#5]
https://github.com/Anton-Utray/ETL

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Antón! Algunos comentarios:

- El repo está bien organizado, con sus carpetas correspondientes. El readme también está muy bien, aunque en futuros proyectos intenta darle un poco menos de extensión (que no de pereza leerlo, más bien al contrario, que enganche. Y a veces nuestra primera mirada suele preferir algo más corto). En ese sentido, muy bien utilizados los desplegables porque precisamente consigues que sea más corto y ya, si el visitante quiere, puede ampliar la información muy facilmente. 
- En cuanto al notebook de la API del gobierno, te felicito por intentarlo hasta conseguirlo. Esa es la mejor actitud aquí. 
- Respecto al de limpieza, muy bien trabajado, además de comentado y organizado. Tenías claro que el foco eran las alcaldías y se nota desde la limpieza.
- Por eso mismo, la base de datos de SQL tal y como la planteas tiene sentido y permite obtener tablas muy enriquecidas y personalizadas.

En general, un gran proyecto, Antón. Me gustaría poder decirte más cosas que mejorar, pero me lo has puesto difícil.

¡Enhorabuena!

**Comment by CharlyKill7** [comment]
Perdona, pero no te comenté nada de la exposición, que se me pasó. A grandes rasgos, muy bien la expo. Algunos comentarios:

-	Muy bien exponer de pie.
-	Intenta mirar más hacia los dos lados de la clase. Sé que es difícil por la disposición de las pantallas, pero ten en cuenta que todos son tu audiencia. 
-	Bien de tiempo, has ido al grano y eso mejora la atención.
