### ISSUE TITLE
[Giotto](project_gamers_etl)

### ISSUE THREAD

**Issue by giottomillan** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#8]
https://github.com/giottomillan/project_gamers.git

**Comment by CharlyKill7** [comment]
Buen proyecto, Giotto! Permíteme algunos comentarios:

- En cuanto al repo, muy buen trabajo. Respetas la estructura de carpetas (aunque intenta que los .csv se queden todos en "data"), y tienes un readme de extensión adecuada que resulta bastante explicativo. Aún así, te recomiendo que imagines cómo vería un visitante externo tu repo en un primer vistazo, porque puede que cueste saber qué archivo se debe abrir entre todos los que tienes en "src".
- También he visto que tienes archivos, como "limpieza_enriquecimiento.py", "scrapping.py" o "load.py", que están esencialmente vacíos. Intenta depurar lo que no sirva para que precisamente sea más fácil de ver dónde tienes todo, como te dije arriba.
- He visto que en el notebook de cleaning tienes lo que parece ser una API Key. Cuando pones los "params" para hacer el scrapeo, pones una key. Si es el caso, esa key ahora es pública y pueden revocártela. Ten cuidado con esas cosas, que a mí en el proyecto final me pasó y me la retiraron cuando más la necesitaba. 
- En cuanto a la carga a SQL y las relaciones, estaría correcto. Echo en falta, a nivel personal, al menos una captura de una súper tabla de varios "join", para ver todos los datos en único frame enriquecido, ya que has optado por no hacerlo en Pandas. 

En general, muy buen proyecto, Giotto. Siempre ando preocupado por si usáis demasiado el chat (sobre todo cuando veo funciones de cierto tamaño y muy comentadas al estilo GPT), pero da la impresión de que lo usas con cabeza y entiendes todo lo que está pasando. Sigue en esta línea pero no te confíes; eso te llevará lejos. 

¡Ánimo!
