### ISSUE TITLE
[David Aparicio] (w4-project_ETL)

### ISSUE THREAD

**Issue by dapafer** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#9]
https://github.com/dapafer/ETL-process

**Comment by CharlyKill7** [comment]
Muy buen proyecto, David! Permíteme algunos comentarios:

- En cuanto al repo, muy bien, David. Queda claro de qué va el proyecto con el readme, está organizado en carpetas , los nombres de archivos son bastante explicativos y en el propio readme indicas dónde acudir y para qué. Además, la estructura HTML es buena y la redaccion también. Muy bien!
- El notebook de scraping está muy bien, consigues lo que te propones y con organización y comentarios muy explicativos. Como único "pero", intenta no hacer imports que luego no vas a usar, como el de BeautifulSoup, por ejemplo. Acostúmbrate a ir importando según vas necesitando, es una buena práctica que te vendrá genial de cara a la optimización.
- En cuanto al notebook de transformación, todo correcto salvo por un detalle. Si te fijas, en el DF prod_df que termina siendo "productos.csv", tienes dos columnas, ancho y alto, que contienen un 96% de pseudo nulos ("desconocido"). Te recomiendo borrar esas dos columnas porque apenas aportan información, y se trata de enriquecer los datos, y generando unknowns consigues un poco lo contrario.
- Bien la conexión a la API y la exportación a SQL.

En cuanto a la exposición que hiciste:
-	Muy bien exponer de pie.
-	Muy bien la presentación PPT, nadie lo pide, pero ayuda mucho y está genial que seáis proactivos en ese sentido.
-	No pongas puntos en los títulos de diapositiva, como en ‘Proceso’. En ‘Extracción’ no lo has puesto.
-	Intenta no dar la espalda a parte de la audiencia. Ciertos ratos, al mirar solo una pantalla, los del otro lado sólo te ven la espalda.
-	Intenta, dentro de lo posible, generar una historia atractiva para el espectador, a través de la cual cuentes tu proceso, pero sin que el proceso sea explícitamente el protagonista.
-	Demasiado largo, intenta ir más al grano en la medida de lo posible, eso mejora el ritmo y mantiene la atención. Decir qué querías y después mostrar lo que conseguiste, sin detenerse demasiado en lo técnico del proceso, puede ayudar a lograr ese mejor ritmo.

En general, un gran proyecto, David. Se ve que vas haciendo acopio de conocimientos y consejos, y se ve reflejado en el paso de los proyectos. En ese sentido, te felicito por no quedarte en la superficie, que fue lo que principalmente te dije en Sharks. Esa es la actitud.

 ¡Enhorabuena, y sigue así!
